Add support for `ListBlock`
wagtail/wagtail-localize pull request #510
Opened 2022-01-21 17:16 UTC by zerolab

2022-02-01 14:53 UTC, kaedroho requested changes
This looks good to me so far. I think we should add a check in to make sure that the blocks have IDs and not extract these

2022-02-01 15:07 UTC, zerolab commented on wagtail_localize/segments/extract.py
> +        if WAGTAIL_VERSION >= (2, 16):
not sure I understand your question.
the `ListBlock` UUID change in 2.16 should provide block IDs if there none, if I understood the PR and the changes correctly

2022-02-01 16:27 UTC, kaedroho commented on wagtail_localize/segments/extract.py
> +        if WAGTAIL_VERSION >= (2, 16):
> the ListBlock UUID change in 2.16 should provide block IDs if there none

I'm not sure if these would be persistent though, it looks like they would be made up on the fly. So the next time they extraction is done, we would be given a different set of IDs.

2022-02-01 17:07 UTC, zerolab commented on wagtail_localize/segments/extract.py
> +        if WAGTAIL_VERSION >= (2, 16):
ah, I see. will need to read into the core handling of it and see if there's a reliable way to check if they have or not IDs

2022-02-02 12:24 UTC, zerolab commented on wagtail_localize/segments/extract.py
> +        if WAGTAIL_VERSION >= (2, 16):
dev note: at the moment this is made tricky by https://github.com/wagtail/wagtail-localize/blob/main/wagtail_localize/segments/extract.py#L142-L146

2022-02-02 14:42 UTC, zerolab commented on wagtail_localize/segments/extract.py
> +        if WAGTAIL_VERSION >= (2, 16):
@kaedroho ok, found an OK-ish solution - 6d130e5
if you have any suggestions for improvement, would love to hear them

2022-02-03 11:33 UTC, kaedroho approved these changes
This looks good to me, thanks!

2022-02-03 11:59 UTC, merged