improve docs for Google Cloud Translate
wagtail/wagtail-localize pull request #575
Opened 2022-05-22 16:49 UTC by chris48s

closes #571

2022-05-22 16:57 UTC, chris48s commented
preview https://deploy-preview-575--wagtail-localize-org.netlify.app/how-to/integrations/machine-translation/

2022-05-23 14:15 UTC, zerolab requested changes
A couple of nitpicks, otherwise looks like a good addition to me.

Thank you @chris48s

2022-05-31 21:07 UTC, zerolab approved these changes

2022-05-31 21:07 UTC, merged

2022-05-31 21:08 UTC, zerolab commented
Thank you @chris48s