Update field-configuration.md
wagtail/wagtail-localize pull request #582
Opened 2022-06-01 16:41 UTC by enzedonline

Added note about StructBlocks

2022-06-01 18:14 UTC, zerolab requested changes

2022-06-01 18:14 UTC, zerolab commented on docs/how-to/field-configuration.md
> +  It is not currently possible to configure StructBlock translatable fields. See [Issue #307](https://github.com/wagtail/wagtail-localize/issues/307) for more details.***
Best to use https://squidfunk.github.io/mkdocs-material/reference/admonitions/
e.g. 

```suggestion
!!! attention
    It is not currently possible to configure `StructBlock` translatable fields. See [Issue #307](https://github.com/wagtail/wagtail-localize/issues/307) for more details.
```

2022-06-05 11:55 UTC, enzedonline commented
I'm trying to be helpful here, not spend 3 hours to add a single sentence to a document 🤦‍♂️

2022-06-05 12:42 UTC, zerolab commented
Thank you @enzedonline, merged in [8502400](https://github.com/wagtail/wagtail-localize/commit/850240053988b2b2cdc1f774beb69adfd2ebffe2)

> I'm trying to be helpful here, not spend 3 hours to add a single sentence to a document 🤦‍♂️

I appreciate the help. It takes a fair amount of time to ensure things like documentation are consistent and that changes make sense. And lot of the time that I put in as a package maintainer is very much my own, personal and unpaid time...

2022-06-05 12:42 UTC, closed without merging