Upgrade for Wagtail 5.0
wagtail/wagtail-localize pull request #697
Opened 2023-05-23 10:33 UTC by nickmoreton

**This work updates the package testing and upgrade considerations for working with Wagtail v5.0**

Also:
- drops support for Django 4.0 (https://docs.wagtail.org/en/stable/releases/5.0.html#dropped-support-for-django-4-0)
- drops support for python 3.7 (end of life is June 2023)

Notable changes from the upgrade considerations:
- Longrunning button class (https://docs.wagtail.org/en/stable/releases/5.0.html#progress-button-button-longrunning-now-relies-on-data-attributes)
- Deprecated icons (https://docs.wagtail.org/en/stable/releases/5.0.html#deprecated-icon-font)

2023-05-23 19:29 UTC, zerolab requested changes
Thank you for making a start, @nickmoreton
There's more work needed. It is worth testing such upgrades with the new Wagtail version, but they always must be tested with the supported versions (usually LTS, and whatever version is before the one you're doing the upgrade).

Unlike sites, packages have to take in consideration multiple Wagtail versions

2023-05-23 19:29 UTC, zerolab commented on wagtail_localize/modeladmin/templates/wagtail_localize/modeladmin/translatable_edit.html
> +    <button type="submit" class="button action-save button-longrunning" data-controller="w-progress" data-action="w-progress#activate" data-w-progress-active-value="{% trans 'Saving…' %}">
have you tested this in Wagtail 4.1? the `data-controller` change only happens in Wagtail 5.0

2023-05-23 19:29 UTC, zerolab commented on wagtail_localize/static_src/editor/components/TranslationEditor/footer.tsx
> +                <Icon name="download" />
Doesn't work with Wagtail < 5.0. Ditto for all icon changes.
The solution would be to add the old icons and register them for Wagtail < 5.0

2023-05-23 19:29 UTC, zerolab commented on wagtail_localize/static_src/editor/components/TranslationEditor/footer.tsx
> -                    data-clicked-text={gettext('Publishing...')}
needs to stay for Wagtail 4.1 compat

2023-05-24 08:12 UTC, nickmoreton commented
> There's more work needed. It is worth testing such upgrades with the new Wagtail version, but they always must be tested with the supported versions (usually LTS, and whatever version is before the one you're doing the upgrade).

Thanks @zerolab How did I not think of that, I've done enough of these 🥲 I'll look again.

2023-06-02 10:28 UTC, zerolab commented
Continued in #699

2023-06-02 10:28 UTC, closed without merging

2023-06-02 10:59 UTC, zerolab commented on wagtail_localize/static_src/editor/components/TranslationEditor/footer.tsx
> +                <Icon name="download" />
looks like I was hasty. 4.0 added all the correctly named icons, so this was good