Add tests with success messages for locale creation, editing, and deletion
wagtail/wagtail-localize pull request #763
Opened 2024-01-07 00:29 UTC by ACK1D

Added tests for #762 (success messages for create, edit, and delete locale). Some logic has been refactored into BaseLocaleTestCase, and correcting some tests for use it. Please review code and let me know if need some work.

2024-01-07 11:22 UTC, ACK1D commented
Hi @zerolab
I've made some changes to code, and it would be helpful to update the Codecov report. Could you please trigger a new run? Thank you!

2024-01-08 09:10 UTC, zerolab commented
@ACK1D thank you very much for this. I am not sure how to make Codecov update its comment, but https://app.codecov.io/gh/wagtail/wagtail-localize/pull/762 shows a +0.11% increase

2024-01-15 22:34 UTC, zerolab requested changes
@ACK1D kudos for expanding the test locales test coverage.
I left a few notes around the consistency of self.client.get/post vs self.get/post which would be nice to tidy up and be consistent about.

2024-01-15 22:34 UTC, zerolab commented on wagtail_localize/locales/tests.py
> -        response = self.post(
`TestLocaleCreateView` still has a `post` method that posts to `reverse("wagtaillocales:add")`. I'd say keep using it, especially that we're using that in at least one other place

2024-01-15 22:34 UTC, zerolab commented on wagtail_localize/locales/tests.py
> +        response = self.client.get(
we now seem to have a mix of `self.client.get` like here, and `self.get` below (like in `test_invalid_language`). It would be nice to be consistent

2024-02-04 11:23 UTC, zerolab approved these changes
Done is better than perfect. Thanks @ACK1D for the tweaks

2024-02-04 11:23 UTC, merged